// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmlngslctmindvcnmqai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tbG5nc2xjdG1pbmR2Y25tcWFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDg0NDgsImV4cCI6MjA2MzgyNDQ0OH0.l_Oc7G_gKU1GRgmyRMAdNNiYU_dCAAldaljqDX4b780";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);